---
abstract: 'take structured address data and format it according to the various global/country rules'
author:
  - 'edf <edf@opencagedata.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.141520'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Geo-Address-Formatter
provides:
  Geo::Address::Formatter:
    file: lib/Geo/Address/Formatter.pm
    version: v1.2.5
requires:
  Clone: '0'
  Data::Dumper: '0'
  File::Find::Rule: '0'
  List::Util: '0'
  Mustache::Simple: '0'
  Test::Exception: '0'
  Test::LWP::Recorder: '0'
  Test::More: '0.88'
  Try::Tiny: '0'
  YAML: '0'
  perl: '5.010'
resources:
  repository: https://github.com/lokku/perl-Geo-Address-Formatter.git
version: 1.2.5
